### ISSUE TITLE
ViewHolder constructor requires TextView parameter.

### ISSUE THREAD

**Issue by leifjones** [PlusJack/Clipboard#1]
We're getting this error:

> ViewHolder (android.widget.TextView) in ViewHolder cannot be applied to (android.view.View)

This refers to [this line in the MyAdapter.java](https://github.com/PlusJack/Clipboard/blob/master/app/src/main/java/com/example/appdevelopment/clipboard/MyAdapter.java#L38).

**Comment by levibostian** [comment]
This exception is because your `ViewHolder` constructor is taking in a `TextView`:

```
    public static class ViewHolder extends RecyclerView.ViewHolder {
        // each data item is just a string in this case
        public TextView mTextView;
        public ViewHolder(TextView v) {  <--------- TextView is constructor. 
            super(v);
            mTextView = v;
        }
    }
```

but when you construct an instance of ViewHolder, you are giving is a `View` object. 

```
        View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.my_text_view, parent, false);
        // set the view's size, margins, paddings and layout parameters as desired
        // ...
        ViewHolder vh = new ViewHolder(v); <------ v is an instance of View. 
```

---

Your ViewHolder constructor should be taking in a View object not TextView. Then you can pull out the textview from the view:

```
    public static class ViewHolder extends RecyclerView.ViewHolder {
        // each data item is just a string in this case
        public TextView mTextView;
        public ViewHolder(View v) {  <--------- View is constructor now. 
            super(v);
            mTextView = v.findViewById(R.id.youridhere); <-- get TextView from the view. 
        }
    }
```

Also, don't return null [here](https://github.com/PlusJack/Clipboard/blob/master/app/src/main/java/com/example/appdevelopment/clipboard/MyAdapter.java#L39). Return your `vh` variable as that is the viewholder.

**Comment by leifjones** [comment]
Switching to View throughout broke prevented `setText()` from working later in the [onBindViewHolder() method](https://github.com/PlusJack/Clipboard/blob/master/app/src/main/java/com/example/appdevelopment/clipboard/MyAdapter.java#L47).

We were stumped on on how to get TextView from View, but by casting inside the ViewHolder constructor, @PlusJack was able to move on:

```
    public static class ViewHolder extends RecyclerView.ViewHolder {
        // each data item is just a string in this case
        public TextView mTextView;
        public ViewHolder(View v) {
            super(v);
            mTextView = (TextView) v.findViewById(R.id.editText); <-- cast View to TextView 
        }
    }
```
